### ISSUE TITLE
Error after install plugin in TeamCity  8.1.2 (build 29993) 

### ISSUE THREAD

**Issue by danimaribeiro** [milgner/TeamCityRedmine#11]
After I've installed the plugin, it deleted all my build configurations, and now when I access the Issue tracker it throws this error.
I installed the last release of the plugin.

<pre>Error message: javax.servlet.jsp.JspException: javax.el.ELException: Cannot read property: name 

Trace: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.el.ELException: Cannot read property: name
    at org.apache.jsp.admin.issueProviders_jsp$Helper.invoke(issueProviders_jsp.java:1220)
    at org.apache.jsp.tag.webrefreshable_tag.doTag(webrefreshable_tag.java:144)
    at org.apache.jsp.admin.issueProviders_jsp._jspx_meth_bs_005frefreshable_005f0(issueProviders_jsp.java:172)
    at org.apache.jsp.admin.issueProviders_jsp._jspService(issueProviders_jsp.java:130)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)

Caused by: java.lang.IllegalStateException: @NotNull method jetbrains/buildServer/issueTracker/impl/IssueProviderWrapper.getName must not return null
    at jetbrains.buildServer.issueTracker.impl.IssueProviderWrapper.getName(IssueProviderWrapper.java:42)
    ... 124 more

</pre>

**Comment by milgner** [comment]
The plugin does not contain any functionality to delete build configurations or do anything. Also the exception stacktrace is inside of Jetbrains' code, which I don't have access to, so I don't know what's happening there.

I'll try installing it on the build version you mentioned and report back once I know whether it works/works not.

**Comment by bruestel** [comment]
I have the same problem with a fresh Teamcity 8.1.x setup.

**Comment by danimaribeiro** [comment]
Sorry guys, I forgot to reply back.
I made work, this is my configuration.
![capturar](https://cloud.githubusercontent.com/assets/854781/3150616/e07b4e4a-ea77-11e3-9372-fd2d55fabf4f.PNG)

If I'm not wrong, I didn't check the option Ignore SSL the first time.
And after restarted the teamcity, all the build configurations were reset.

Feel free to close this issue, it works fine if you don't make mistake in the configuration.

**Comment by milgner** [comment]
This is still very suspicious. I have no idea why TC would reset the build configurations. Do you happen to have another stacktrace maybe? The one above isn't related to my code and I'm not aware of any API changes (it shouldn't even compile in that case). But as I happen to have some free time on my hands at the moment, I'll do some more research on the subject.

**Comment by danimaribeiro** [comment]
Hey, I was able to reproduce part of the problem.

This is the configuration that originates the problem, if you don't tick Ignore SSL?
![capturariii](https://cloud.githubusercontent.com/assets/854781/3200627/a09349ea-ed7e-11e3-8096-454a4743239b.PNG)

This is the page error.
![capturariv](https://cloud.githubusercontent.com/assets/854781/3200626/a0901554-ed7e-11e3-864f-e6c9ac68f931.PNG)

But it didn't deleted any of build configurations this time, so maybe I did a mistake last time.

And here the full stack trace.

```
2014-06-06 10:22:46,557]  ERROR -   jetbrains.buildServer.SERVER - Error javax.el.ELException: Cannot read property: name while processing request: GET '/admin/admin.html?item=issueTracker', from client 0:0:0:0:0:0:0:1:49399, authenticated as 'danimar' (Danimar) {id=1} 
javax.el.ELException: Cannot read property: name
    at jetbrains.buildServer.web.jsp.TCBeanELResolver.getValue(TCBeanELResolver.java:71)
    at org.apache.jasper.el.JasperELResolver.getValue(JasperELResolver.java:104)
    at org.apache.el.parser.AstValue.getValue(AstValue.java:183)
    at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:185)
    at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:1026)
    at org.apache.jsp.admin.issueProviders_jsp._jspx_meth_c_005fset_005f2(issueProviders_jsp.java:443)
    at org.apache.jsp.admin.issueProviders_jsp._jspx_meth_c_005fforEach_005f0(issueProviders_jsp.java:352)
    at org.apache.jsp.admin.issueProviders_jsp.access$5(issueProviders_jsp.java:327)
    at org.apache.jsp.admin.issueProviders_jsp$Helper.invoke1(issueProviders_jsp.java:1028)
    at org.apache.jsp.admin.issueProviders_jsp$Helper.invoke(issueProviders_jsp.java:1194)
    at org.apache.jsp.tag.weblayout.tableWithHighlighting_tag.doTag(tableWithHighlighting_tag.java:163)
    at org.apache.jsp.admin.issueProviders_jsp._jspx_meth_l_005ftableWithHighlighting_005f0(issueProviders_jsp.java:322)
    at org.apache.jsp.admin.issueProviders_jsp._jspx_meth_c_005fwhen_005f0(issueProviders_jsp.java:289)
    at org.apache.jsp.admin.issueProviders_jsp._jspx_meth_c_005fchoose_005f0(issueProviders_jsp.java:257)
    at org.apache.jsp.admin.issueProviders_jsp.access$3(issueProviders_jsp.java:244)
    at org.apache.jsp.admin.issueProviders_jsp$Helper.invoke0(issueProviders_jsp.java:1004)
    at org.apache.jsp.admin.issueProviders_jsp$Helper.invoke(issueProviders_jsp.java:1191)
    at org.apache.jsp.tag.webrefreshable_tag.doTag(webrefreshable_tag.java:144)
    at org.apache.jsp.admin.issueProviders_jsp._jspx_meth_bs_005frefreshable_005f0(issueProviders_jsp.java:172)
    at org.apache.jsp.admin.issueProviders_jsp._jspService(issueProviders_jsp.java:130)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
    at jetbrains.spring.web.TeamCityJSPServletImpl.access$001(TeamCityJSPServletImpl.java:7)
    at jetbrains.spring.web.TeamCityJSPServletImpl$1.apply(TeamCityJSPServletImpl.java:2)
    at jetbrains.buildServer.util.Util.doUnderContextClassLoader(Util.java:68)
    at jetbrains.spring.web.TeamCityJSPServletImpl.service(TeamCityJSPServletImpl.java:1)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at jetbrains.spring.web.JspController.doHandle(JspController.java:0)
    at jetbrains.buildServer.controllers.BaseController.handleRequestInternal(BaseController.java:75)
    at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
    at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:790)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:549)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:37)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749)
    at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:605)
    at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:544)
    at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:954)
    at org.apache.jsp.tag.webext.includeExtension_tag._jspx_meth_c_005fif_005f3(includeExtension_tag.java:521)
    at org.apache.jsp.tag.webext.includeExtension_tag._jspx_meth_c_005fif_005f0(includeExtension_tag.java:184)
    at org.apache.jsp.tag.webext.includeExtension_tag.doTag(includeExtension_tag.java:148)
    at org.apache.jsp.admin.adminMain_jsp._jspx_meth_ext_005fincludeExtension_005f0(adminMain_jsp.java:260)
    at org.apache.jsp.admin.adminMain_jsp.access$6(adminMain_jsp.java:249)
    at org.apache.jsp.admin.adminMain_jsp$Helper.invoke3(adminMain_jsp.java:351)
    at org.apache.jsp.admin.adminMain_jsp$Helper.invoke(adminMain_jsp.java:382)
    at org.apache.jsp.tag.webpage_tag.doTag(webpage_tag.java:557)
    at org.apache.jsp.admin.adminMain_jsp._jspx_meth_bs_005fpage_005f0(adminMain_jsp.java:142)
    at org.apache.jsp.admin.adminMain_jsp._jspService(adminMain_jsp.java:111)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
    at jetbrains.spring.web.TeamCityJSPServletImpl.access$001(TeamCityJSPServletImpl.java:7)
    at jetbrains.spring.web.TeamCityJSPServletImpl$1.apply(TeamCityJSPServletImpl.java:2)
    at jetbrains.buildServer.util.Util.doUnderContextClassLoader(Util.java:68)
    at jetbrains.spring.web.TeamCityJSPServletImpl.service(TeamCityJSPServletImpl.java:1)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at jetbrains.spring.web.JspController.doHandle(JspController.java:0)
    at jetbrains.buildServer.controllers.BaseController.handleRequestInternal(BaseController.java:75)
    at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
    at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:790)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:549)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:37)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749)
    at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:487)
    at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:412)
    at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:339)
    at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:238)
    at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:250)
    at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1047)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:817)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:549)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:37)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at jetbrains.buildServer.web.ParametersProviderCalculationContextFilter.doFilter(ParametersProviderCalculationContextFilter.java:6)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at jetbrains.buildServer.web.DisableSessionIdFromUrlFilter.doFilter(DisableSessionIdFromUrlFilter.java:3)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at jetbrains.buildServer.web.DiagnosticFilter.doFilter(DiagnosticFilter.java:26)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at jetbrains.buildServer.web.ResponseFragmentFilter.doFilter(ResponseFragmentFilter.java:11)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1686)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at jetbrains.buildServer.web.jsp.TCBeanELResolver.getValue(TCBeanELResolver.java:56)
    ... 119 more
Caused by: java.lang.IllegalStateException: @NotNull method jetbrains/buildServer/issueTracker/impl/IssueProviderWrapper.getName must not return null
    at jetbrains.buildServer.issueTracker.impl.IssueProviderWrapper.getName(IssueProviderWrapper.java:42)
    ... 123 more

```

**Comment by milgner** [comment]
Unfortunately haven't been able to reproduce. Will tacke 9.0 compatibility for now. Please open a new issue if it can be reproduced there once that's done.
